Repository UNIZAR-30246-WebEngineering/lab1-git-race, pull requests merged in 2020-09, with the labels that each got.

#10 PR Victor Martinez
  README.md
  description.md
  src/main/resources/application.properties
  src/main/resources/static/images/Pilar.jpg
  src/main/webapp/WEB-INF/jsp/wellcome.jsp
Labels: question

#14 PR Luis Garcia Garces
  README.md
  description.md
  src/main/java/es/unizar/webeng/hello/RingsQuote.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/jsp/lordrings.jsp
Labels: question

#18 New functionality added, new number system converter.
  README.md
  src/main/java/es/unizar/webeng/hello/BaseConverterController.java
  src/main/resources/templates/converter.html
  src/test/java/es/unizar/webeng/hello/BaseConverterUnitTest.java
Labels: bug, enhancement

#21 PR Jorge: Spring II - use WebClient for sync request - Twitter Timeline functionality
  README.md
  build.gradle
  description.md
  src/main/java/es/unizar/webeng/hello/Application.java
  src/main/java/es/unizar/webeng/hello/TweetController.java
  src/main/resources/application.properties
  src/main/resources/templates/tweet.html
Labels: enhancement

#20 Google Cloud Kubernetes deployment, Docker fixes
  Dockerfile
  README.md
  description.md
Labels: enhancement
