Repository UNIZAR-30246-WebEngineering/lab1-git-race, pull requests merged in 2021-10, with the labels that each got.

#18 new get route added
  .gitignore
  README.md
  src/main/kotlin/controller/HelloController.kt
  src/main/resources/templates/new.html
  src/test/kotlin/controller/NewControllerMVCTests.kt
  src/test/kotlin/controller/NewControllerUnitTests.kt
Labels: bug, changes requested

#19 Redis persistent support for a new /game endpoint.
  README.md
  build.gradle.kts
  redis.yml
  src/main/kotlin/controller/GameController.kt
  src/main/resources/templates/game.html
  src/test/kotlin/controller/GameControllerMVCTests.kt
Labels: changes requested

#20 Using an endpoint that returns the message and updating the HTML in client side
  README.md
  src/main/kotlin/controller/HelloController.kt
  src/main/kotlin/controller/RestController.kt
  src/main/resources/templates/restAPIPage.html
Labels: enhancement, gift

#29 nia is even
  README.md
  src/main/kotlin/controller/HelloController.kt
  src/main/resources/templates/new.html
Labels: under review

#34 How to fix the "Localhost refused to connect" issue
  README.md
  description.md
Labels: enhancement
