Repository UNIZAR-30246-WebEngineering/lab1-git-race, pull requests merged in 2021-09, with the labels that each got.

#5 Documentation for the HTML / CSS Tests
  README.md
  description.md
Labels: enhancement

#8 Added description on how to test code
  README.md
  description.md
Labels: enhancement

#9 Added explanation for gradle build file
  README.md
  build.gradle.kts
  description.md
Labels: enhancement

#10 Added explanation about the controller
  README.md
  description.md
  src/main/kotlin/controller/HelloController.kt
Labels: enhancement

#7 Added comments to Integration Test
  README.md
  src/test/kotlin/IntegrationTest.kt
Labels: enhancement

#11 Custom Error page
  README.md
  description.md
  src/main/resources/public/assets/error.png
  src/main/resources/templates/error.html
Labels: enhancement

#12 Added comments for HelloController Unit Tests
  README.md
  src/test/kotlin/controller/HelloControllerUnitTests.kt
Labels: enhancement

#14 MVC Test controller docs
  README.md
  src/test/kotlin/controller/HelloControllerMVCTests.kt
Labels: under review

#16 Added "How to deploy the code in Heroku"
  .gitignore
  README.md
  build.gradle.kts
  description.md
Labels: enhancement

#4 Dockerfile + Deploy - AT THE ESTABLISHED TIME!!
  Dockerfile
  README.md
  description.md
Labels: changes requested

#1 doc set up
  description.md
Labels: changes requested

#2 Docker
  README.md
  description.md
Labels: bug, changes requested

#6 Deployment using docker-compose and doc associated
  README.md
  description.md
  docker-compose.yml
Labels: enhancement, gift

#13 Kotlin app deployed in Minikube Cluster
  Dockerfile
  README.md
  charts/Chart.yaml
  charts/templates/deployment.yaml
  charts/templates/service.yaml
  charts/values.yaml
  description.md
Labels: enhancement, gift

#15 HelloControllerMVCTest doc
  README.md
  src/test/kotlin/controller/HelloControllerMVCTests.kt
Labels: enhancement

#17 Using another markup template language
  README.md
  build.gradle.kts
  src/main/kotlin/controller/HelloController.kt
  src/main/resources/application.properties
  src/main/resources/templates/hello.mustache
Labels: changes requested
